[tool.poetry]
name = "project-2-garamov-26-555"
version = "0.1.0"
description = "Primitive database project"
authors = ["Nikita Garamov"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
project = "src.primitive_db.main:main"
